### ISSUE TITLE
drag&drop of image into "empty space" causes segfault

### ISSUE THREAD

**Issue by yarikoptic** [phase1geo/Minder#508]
I tried drag&dropping this image https://pj.freefaculty.org/guides/crmda_guides/31.git/images/phd101212s.gif into a new mind map where I deselected "Main idea". That caused segfault 

<details>
<summary>click here to expand for full gdb traceback etc</summary> 

```shell
❯ gdb --args /usr/bin/com.github.phase1geo.minder
GNU gdb (Debian 12.1-3) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/com.github.phase1geo.minder...
Reading symbols from /usr/lib/debug/.build-id/9c/21b63bfdbd9f9c89f3e3e168863f3e8d2dc4df.debug...
(gdb) r
Starting program: /usr/bin/com.github.phase1geo.minder 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff31ff640 (LWP 2028985)]
[New Thread 0x7ffff29fe640 (LWP 2028986)]
[New Thread 0x7ffff20d6640 (LWP 2028987)]
[New Thread 0x7ffff18d5640 (LWP 2028988)]
[Thread 0x7ffff18d5640 (LWP 2028988) exited]
[New Thread 0x7ffff18d5640 (LWP 2028989)]
[New Thread 0x7ffff09ff640 (LWP 2028990)]
[Thread 0x7ffff18d5640 (LWP 2028989) exited]
[New Thread 0x7ffff18d5640 (LWP 2028991)]
[New Thread 0x7fffdbfff640 (LWP 2028992)]
[Thread 0x7ffff09ff640 (LWP 2028990) exited]
[Thread 0x7ffff18d5640 (LWP 2028991) exited]
[Thread 0x7fffdbfff640 (LWP 2028992) exited]
[New Thread 0x7fffdbfff640 (LWP 2028993)]
[New Thread 0x7ffff18d5640 (LWP 2028995)]
[New Thread 0x7ffff09ff640 (LWP 2028996)]
[Thread 0x7ffff18d5640 (LWP 2028995) exited]
[New Thread 0x7ffff18d5640 (LWP 2028997)]
[New Thread 0x7fffdabff640 (LWP 2028998)]
[Thread 0x7ffff09ff640 (LWP 2028996) exited]
[Thread 0x7ffff18d5640 (LWP 2028997) exited]
[Thread 0x7fffdabff640 (LWP 2028998) exited]
[New Thread 0x7fffdabff640 (LWP 2028999)]
[New Thread 0x7ffff18d5640 (LWP 2029000)]
[Thread 0x7fffdabff640 (LWP 2028999) exited]
[New Thread 0x7fffdabff640 (LWP 2029001)]
[New Thread 0x7ffff09ff640 (LWP 2029002)]
[Thread 0x7ffff18d5640 (LWP 2029000) exited]
[Thread 0x7fffdabff640 (LWP 2029001) exited]
[Thread 0x7ffff09ff640 (LWP 2029002) exited]
[New Thread 0x7ffff09ff640 (LWP 2029003)]
[New Thread 0x7fffdabff640 (LWP 2029004)]
[Thread 0x7ffff09ff640 (LWP 2029003) exited]
[New Thread 0x7ffff09ff640 (LWP 2029005)]
[New Thread 0x7ffff18d5640 (LWP 2029006)]
[Thread 0x7fffdabff640 (LWP 2029004) exited]
[Thread 0x7ffff09ff640 (LWP 2029005) exited]
[Thread 0x7ffff18d5640 (LWP 2029006) exited]
[New Thread 0x7ffff18d5640 (LWP 2029007)]
[New Thread 0x7ffff09ff640 (LWP 2029008)]
[Thread 0x7ffff18d5640 (LWP 2029007) exited]
[New Thread 0x7ffff18d5640 (LWP 2029009)]
[New Thread 0x7fffdabff640 (LWP 2029010)]
[Thread 0x7ffff09ff640 (LWP 2029008) exited]
[Thread 0x7ffff18d5640 (LWP 2029009) exited]
[Thread 0x7fffdabff640 (LWP 2029010) exited]
I/O warning : failed to load external entity "/home/yoh/.local/share/minder/unnamed3.minder"

Thread 1 "com.github.phas" received signal SIGSEGV, Segmentation fault.
0x000055555564cf21 in style_inspector_update_ui_with_style (self=0x555555cd4240, style=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
) at com.github.phase1geo.minder.p/src/StyleInspector.c:5519
5519	com.github.phase1geo.minder.p/src/StyleInspector.c: No such file or directory.
(gdb) bt
#0  0x000055555564cf21 in style_inspector_update_ui_with_stylePython Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
 (self=0x555555cd4240, style=)
    at com.github.phase1geo.minder.p/src/StyleInspector.c:5519
#1  0x000055555564db59 in style_inspector_handle_current_changed (self=0x555555cd4240)
    at com.github.phase1geo.minder.p/src/StyleInspector.c:5637
#2  _style_inspector_handle_current_changed_draw_area_current_changed
    (_sender=<optimized out>, da=<optimized out>, self=0x555555cd4240)
    at com.github.phase1geo.minder.p/src/StyleInspector.c:1313
#3  0x00007ffff7f45570 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff7f577e6 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff7f5de47 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff7f5e33f in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7f45570 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7f577e6 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7f5de47 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff7f5e33f in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x000055555563aa9a in selection_add_nodePython Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
 (self=, node=0x555556bf8750, signal_change=1)
    at com.github.phase1geo.minder.p/src/Selection.c:938
#12 0x00005555555d3417 in draw_area_select_node (animate=1, n=0x555556bf8750, self=0x555556a03290)
    at com.github.phase1geo.minder.p/src/DrawArea.c:12614
#13 draw_area_select_node (self=0x555556a03290, n=0x555556bf8750, animate=1)
    at com.github.phase1geo.minder.p/src/DrawArea.c:12576
#14 0x00005555555dc35c in draw_area_handle_drag_data_received
    (t=358771976, info=<optimized out>, data=<optimized out>, y=<optimized out>, x=<optimized out>, ctx=0x555556b4db40, self=0x555556a03290) at com.github.phase1geo.minder.p/src/DrawArea.c:21849
#15 _draw_area_handle_drag_data_received_gtk_widget_drag_data_received
    (_sender=<optimized out>, context=0x555556b4db40, x=<optimized out>, y=<optimized out>, selection_data=<optimized out>, info=<optimized out>, time_=358771976, self=0x555556a03290) at com.github.phase1geo.minder.p/src/DrawArea.c:3827
#16 0x00007ffff75f0a05 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff7f45769 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff7f5e197 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff7f5e558 in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff75c16b8 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff75ee202 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff7f45769 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff7f5e197 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff7f5e558 in g_signal_emit_by_name () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff74d7486 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff75e9144 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff7f45769 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff7f5d574 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff7f5e33f in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff7593554 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff744aee5 in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff7a9b5a5 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#33 0x00007ffff7acf5b2 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#34 0x00007ffff7e4dbc9 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff7e4de58 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff7e4e10f in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff744a265 in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00005555555b6538 in minder_real_activate (base=0x5555557cc1c0) at com.github.phase1geo.minder.p/src/Application.c:466
#39 0x00007ffff7f45769 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00007ffff7f5e197 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x00007ffff7f5e33f in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#42 0x00007ffff70652d8 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#43 0x00007ffff7065466 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#44 0x000055555556fec6 in minder_main (args_length1=<optimized out>, args=<optimized out>)
    at com.github.phase1geo.minder.p/src/Application.c:654
#45 main (argc=<optimized out>, argv=<optimized out>) at com.github.phase1geo.minder.p/src/Application.c:664

```
</details>

minder -- installed on debian gnu linux

```shell
❯ apt-cache policy minder
minder:
  Installed: 1.14.0-1
  Candidate: 1.14.0-1
  Version table:
 *** 1.14.0-1 900
        900 http://deb.debian.org/debian bookworm/main amd64 Packages
        600 http://http.debian.net/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by phase1geo** [comment]
Could you try building and running the latest master branch? I think I have fixed this issue there.

**Comment by yarikoptic** [comment]
Thanks for the quick follow up!  I have rebuilt it (as of 1.14.0+git62-g40ec41e)  as an updated debian package, tried it -- worked great. So I uploaded that snapshot build to NeuroDebian (http://neuro.debian.net/) in case someone wants to give it a shot too over the one they find in their debian/ubuntu release.
