### ISSUE TITLE
segfaults on groupping

### ISSUE THREAD

**Issue by yarikoptic** [phase1geo/Minder#509]
just happily closed #508 to just discover another way to segfault.

<details>
<summary>traceback from gdb while running `1.14.0+git62-g40ec41e-1~nd+1` debian built uploaded to neurodebian</summary> 

```shell
Thread 1 "com.github.phas" received signal SIGSEGV, Segmentation fault.
node_group_construct_array (object_type=<optimized out>, da=da@entry=0x555556ab0500, nodes=nodes@entry=0x555556a16a30) at com.github.phase1geo.minder.p/src/NodeGroup.c:413
413	com.github.phase1geo.minder.p/src/NodeGroup.c: No such file or directory.
(gdb) bt
#0  node_group_construct_array (object_type=<optimized out>, da=da@entry=0x555556ab0500, nodes=nodes@entry=0x555556a16a30)
    at com.github.phase1geo.minder.p/src/NodeGroup.c:413
#1  0x000055555562a545 in node_group_new_array (da=da@entry=0x555556ab0500, nodes=nodes@entry=0x555556a16a30)
    at com.github.phase1geo.minder.p/src/NodeGroup.c:448
#2  0x00005555555de36e in draw_area_add_group (self=0x555556ab0500) at com.github.phase1geo.minder.p/src/DrawArea.c:6637
#3  0x00005555555e3f86 in draw_area_on_keypress (e=0x5555569dfb40, self=0x555556ab0500)
    at com.github.phase1geo.minder.p/src/DrawArea.c:18725
#4  _draw_area_on_keypress_gtk_widget_key_press_event
    (_sender=_sender@entry=0x555556ab0500, event=0x5555569dfb40, self=0x555556ab0500)
    at com.github.phase1geo.minder.p/src/DrawArea.c:3782
#5  0x00007ffff75e9057 in _gtk_marshal_BOOLEAN__BOXED
    (closure=0x555556b7b360, return_value=0x7fffffffcf80, n_param_values=<optimized out>, param_values=0x7fffffffcfe0, invocation_hint=<optimized out>, marshal_data=<optimized out>) at ./debian/build/deb/gtk/gtkmarshalers.c:83
#6  0x00007ffff7f45570 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7f577e6 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7f5d965 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7f5e33f in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff7593554 in gtk_widget_event_internal (widget=widget@entry=0x555556ab0500, event=event@entry=0x5555569dfb40)
    at ../../../../gtk/gtkwidget.c:7812
#11 0x00007ffff7595e91 in gtk_widget_event_internal (event=0x5555569dfb40, widget=0x555556ab0500)
    at ../../../../gtk/gtkwidget.c:7383
#12 0x00007ffff75b485b in gtk_window_propagate_key_event (window=window@entry=0x5555558fa680, event=event@entry=0x5555569dfb40)
    at ../../../../gtk/gtkwindow.c:8224
#13 0x00007ffff75b8bcb in gtk_window_key_press_event (widget=0x5555558fa680, event=0x5555569dfb40)
    at ../../../../gtk/gtkwindow.c:8257
#14 0x00007ffff75e9144 in _gtk_marshal_BOOLEAN__BOXEDv
    (closure=0x55555584dc50, return_value=0x7fffffffd480, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x55555584dc80) at ./debian/build/deb/gtk/gtkmarshalers.c:129
#15 0x00007ffff7f45769 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff7f5d574 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff7f5e33f in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff7593554 in gtk_widget_event_internal (widget=0x5555558fa680, event=0x5555569dfb40)
    at ../../../../gtk/gtkwidget.c:7812
#19 0x00007ffff74496ff in propagate_event (widget=0x5555558fa680, event=0x5555569dfb40, captured=<optimized out>, topmost=0x0)
    at ../../../../gtk/gtkmain.c:2691
#20 0x00007ffff744b066 in gtk_main_do_event (event=0x5555569dfb40) at ../../../../gtk/gtkmain.c:1921
#21 gtk_main_do_event (event=<optimized out>) at ../../../../gtk/gtkmain.c:1691
#22 0x00007ffff7a9b5a5 in _gdk_event_emit (event=event@entry=0x5555569dfb40) at ../../../../gdk/gdkevents.c:73
#23 0x00007ffff7acf5b2 in gdk_event_source_dispatch
    (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../../../../../gdk/x11/gdkeventsource.c:367
#24 0x00007ffff7e4dbc9 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff7e4de58 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff7e4e10f in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff744a265 in gtk_main () at ../../../../gtk/gtkmain.c:1329
#28 0x00005555555b7968 in minder_real_activate (base=0x5555557d01e0) at com.github.phase1geo.minder.p/src/Application.c:637
#29 minder_real_activate (base=0x5555557d01e0) at com.github.phase1geo.minder.p/src/Application.c:626
#30 0x00007ffff7f45769 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff7f5e197 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff7f5e33f in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff70652d8 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#34 0x00007ffff7065466 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#35 0x00005555555701c0 in minder_main (args_length1=<optimized out>, args=<optimized out>)
    at com.github.phase1geo.minder.p/src/Application.c:1101
#36 main (argc=<optimized out>, argv=<optimized out>) at com.github.phase1geo.minder.p/src/Application.c:1111

```
</details>

it happens on [pics/DataLad-minder.svg](https://datasets.datalad.org/centerforopenneuroscience/talks/pics/DataLad.minder) (from repo which could be cloned from https://datasets.datalad.org/centerforopenneuroscience/talks/.git/ and committish a2386fbae2003dd8d0270b99516f9f77b4d9f639 and browsed [here](https://datasets.datalad.org/?dir=/centerforopenneuroscience/talks/pics)).

when I try to group the "legend" elements on the left top:
![image](https://user-images.githubusercontent.com/39889/190494577-ef714dce-f62a-48f9-916e-f81fe54c68ad.png)

and press g -- segfault

**Comment by phase1geo** [comment]
The segmentation fault issue should be fixed in the master branch now.
